### ISSUE TITLE
PAPreferencesDidChangeNotification notification does not have userInfo about property that changed

### ISSUE THREAD

**Issue by evgeniyd** [dhennessy/PAPreferences#22]
When receiving `NSNotification` from `PAPreferences` instance, it does not have info about what exactly the property name that is changed.
It would be useful to have such an info, so the callback can easily update other data/UI upon the change.

**Comment by dhennessy** [comment]
Actually, the notification does contain the name of the property that changed (keyed by `PAPreferencesChangedPropertyKey`). Additionally, you can use KVO to observe individual properties.

**Comment by evgeniyd** [comment]
This was caused by another issue #23
