### ISSUE TITLE
Tag in Podspec should be updated for latest commits

### ISSUE THREAD

**Issue by evgeniyd** [dhennessy/PAPreferences#23]
Current `.podspec` points to tag 0.4, which itself targeted to a commit made at Nov 19

```
s.version      = "0.4"

# other things...

s.source       = { :git => 'https://github.com/dhennessy/PAPreferences.git', :tag => s.version.to_s } 
```

I can submit a pull request with these changes.

**Comment by dhennessy** [comment]
I think it might be simplest if I made a new cocoapods release since the new spec has to be submitted to the cocoapods repo as well. I'll try to get to that later today.

**Comment by dhennessy** [comment]
Version 0.5 now pushed to cocoapods.

**Comment by evgeniyd** [comment]
This works. Thanks.
